### GET ALL POSTS
GET http://localhost:3000/posts

### GET SINGLE POST
GET http://localhost:3000/posts/670016b0d5ab8b5466b0d88e

### CREATE POST
POST http://localhost:3000/posts
Content-Type: application/json

{
  "title": "test",
  "content":"some random content",
  "category":"Testing",
  "tags": ["Test", "API"]
}

### UPDATE POST

### DELETE POST