### GET ALL POSTS
GET http://localhost:3000/posts

### GET SINGLE POST
GET http://localhost:3000/posts/670016b0d5ab8b5466b0d88e

### CREATE POST
POST http://localhost:3000/posts
Content-Type: application/json

{
  "title": "testing the api once more2",
  "content":"the content for today is testing my amazing api 😁",
  "category":"Testing",
  "tags": []
}

### UPDATE POST
PUT http://localhost:3000/posts/670016b0d5ab8b5466b0d88e
Content-Type: application/json

{
  "title": "test2",
  "content":"edited content",
  "category":"Testing",
  "tags": ["Edit"]
}

### DELETE POST
DELETE http://localhost:3000/posts/670016b0d5ab8b5466b0d88e